const dummyData = [
    {
        fname: "Dheeraj",
        lname: "Gogoi",
        department: "Computer Science and Engineering",
        programme: "Bachelor of Technology",
        enrollment_no: "CSB20028",
        phone: "7099485845",
        personal_email: "dheerajgogoi2@gmail.com",
        tezu_email: "csb20028@tezu.ac.in",
    },
    {
        fname: "John",
        lname: "Doe",
        department: "Computer Science and Engineering",
        programme: "Bachelor of Science",
        enrollment_no: "CSB20029",
        phone: "1234567890",
        personal_email: "john.doe@example.com",
        tezu_email: "eeb12345@tezu.ac.in",
    },
    {
        fname: "Alice",
        lname: "Smith",
        department: "Computer Science and Engineering",
        programme: "Master of Technology",
        enrollment_no: "CSB20030",
        phone: "9876543210",
        personal_email: "alice.smith@example.com",
        tezu_email: "meb67890@tezu.ac.in",
    },
    {
        fname: "Bob",
        lname: "Johnson",
        department: "Computer Science and Engineering",
        programme: "Bachelor of Technology",
        enrollment_no: "CSB20031",
        phone: "5551234567",
        personal_email: "bob.johnson@example.com",
        tezu_email: "ceb13579@tezu.ac.in",
    },
    {
        fname: "Eva",
        lname: "Williams",
        department: "Computer Science and Engineering",
        programme: "Master of Science",
        enrollment_no: "CSB20032",
        phone: "1239874560",
        personal_email: "eva.williams@example.com",
        tezu_email: "msc20032@tezu.ac.in",
    },
    {
        fname: "Michael",
        lname: "Brown",
        department: "Computer Science and Engineering",
        programme: "Bachelor of Technology",
        enrollment_no: "CSB20033",
        phone: "7894561230",
        personal_email: "michael.brown@example.com",
        tezu_email: "csb20033@tezu.ac.in",
    },
    {
        fname: "Emma",
        lname: "Anderson",
        department: "Computer Science and Engineering",
        programme: "Master of Technology",
        enrollment_no: "CSB20034",
        phone: "4567890123",
        personal_email: "emma.anderson@example.com",
        tezu_email: "mt20034@tezu.ac.in",
    },
    {
        fname: "Ryan",
        lname: "Johnson",
        department: "Computer Science and Engineering",
        programme: "Bachelor of Science",
        enrollment_no: "CSB20035",
        phone: "9870123456",
        personal_email: "ryan.johnson@example.com",
        tezu_email: "bsc20035@tezu.ac.in",
    },
    {
        fname: "Sophia",
        lname: "Miller",
        department: "Computer Science and Engineering",
        programme: "Master of Technology",
        enrollment_no: "CSB20036",
        phone: "6543210987",
        personal_email: "sophia.miller@example.com",
        tezu_email: "mt20036@tezu.ac.in",
    },
    {
        fname: "Oliver",
        lname: "Davis",
        department: "Computer Science and Engineering",
        programme: "Bachelor of Technology",
        enrollment_no: "CSB20037",
        phone: "3210987654",
        personal_email: "oliver.davis@example.com",
        tezu_email: "csb20037@tezu.ac.in",
    },
];
